version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8008:8008
    env_file:
      - ./.env
    # network_mode: "host"        
    restart: unless-stopped
    depends_on:
      - db
  db:
    # network_mode: "host"        
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=acc-gen1
      - POSTGRES_PASSWORD=acc-gen1
      - POSTGRES_DB=acc-gen1
    restart: always

volumes:
  postgres_data:
